### ISSUE TITLE
masTrans not created, pre-trained model downloaded each time

### ISSUE THREAD

**Issue by AlessioDelConte** [deemeng/embedding#6]
Hello,

I have some problems while executing the container (v2) on a test sequence. I have a fasta file and the a3m file (output of hhblits), but when I run the container I only get the outputs from the onehot encoding and the protTrans (see attached image). In the logging I do not see any error of sort.

![image](https://github.com/deemeng/embedding/assets/15822575/dc009491-5999-41a4-a331-46a4567e0955)

![image](https://github.com/deemeng/embedding/assets/15822575/3001a31c-e1ed-49d2-8cd7-48b5e3d21ec9)

Moreover, each time that I run the container it will download the pythorch_model.bin file which is quite heavy (11.3Gb). It would be really helpful to extract this model so when launching the container it can be mounted as additional input file and avoiding to re-download it each time. This is also true for the other models being downloaded (esm_msa1b_t12_100M_UR50S.pt and  esm_msa1b_t12_100M_UR50S-contact-regression.pt). I think in the code you can then just pass the path to the pre downloaded model.

Best,
Alessio

**Comment by deemeng** [comment]
Hi Alessio,

Thank you for addressing these issues and providing advice. The reason why no msaTrans embedded sequence was generated is because the MSA Transformer can only handle sequences with a length of <= 1022. I have added some print statements in the code to clarify this.

The Loading model part is solved too. 

Please check the newest version dimeng851/embedding:v3.

Let me know if there is any issue. 

Best,
Di.

**Comment by AlessioDelConte** [comment]
Hi Di,

I've tested the version 3 of the docker image it and it works perfectly now!

Thanks a lot,
Alessio
